### ISSUE TITLE
Verify inter-service dependencies before publishing release

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/PlaceOS#1]
Encapsulate release tasks in a docker container that will be run as a verification action before cutting a release.

Useful tasks
- Verify all services have a specific shard within a semver range
- Verify all services built against the same crystal compiler

**Comment by kimburgess** [comment]
It should be possible to integrate this directly as a step within the actions config (without needing a container). 

@caspiano can you define the requirements a little more tightly (e.g. exact versions matches?)

**Comment by caspiano** [comment]
Made a minor edit

**Comment by kimburgess** [comment]
Is there a preference to define these explicitly, or just verify that all services share the same / compatible versions?

**Comment by caspiano** [comment]
I think same/compatible versions would be a lot more complicated than specifying semver ranges for a set of shards. There's probably only a few shards that we really care about in terms of ensuring consistency across services... like DB drivers, or any shared interfaces.

**Comment by kimburgess** [comment]
How about defining two checks for dependencies:
1. *Consistency*: specifies a shard that should use a consistent version (either _major.minor_, or an exact match if we need that level of strictness) across all services. Checking this should be relatively simple. The main intent here is to ensure compatibility without having to manually update this tooling to reference specific version ranges.
2. *Version Range*: use the [same semantic as the shards spec](https://github.com/crystal-lang/shards/blob/master/SPEC.md#version-1) to specify min / max / exact versions allowable in release builds.

**Comment by caspiano** [comment]
Shard report action suffices for a manual check ATM

**Comment by caspiano** [comment]
Also, crystal version is a build arg, and is consistent across all services.
